### ISSUE TITLE
rhocall annotate error

### ISSUE THREAD

**Issue by henrikstranneheim** [dnil/rhocall#8]
rhocall annotate -r 118_sorted_md_brecal_gvcf_vrecal_comb_BOTH.roh ../develop/118/analysis/118/bwa/118_sorted_md_brecal_gvcf_vrecal_comb_BOTH.bcf -o test.vcf.roh.vcf
Traceback (most recent call last):
  File "/mnt/hds/proj/cust003/develop/modules/miniconda2/envs/mip4.0/bin/rhocall", line 11, in <module>
    load_entry_point('rhocall', 'console_scripts', 'rhocall')()
  File "/mnt/hds/proj/cust003/develop/modules/miniconda2/envs/mip4.0/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/mnt/hds/proj/cust003/develop/modules/miniconda2/envs/mip4.0/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/mnt/hds/proj/cust003/develop/modules/miniconda2/envs/mip4.0/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/mnt/hds/proj/cust003/develop/modules/miniconda2/envs/mip4.0/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mnt/hds/proj/cust003/develop/modules/miniconda2/envs/mip4.0/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/mnt/hds/proj/cust003/modules/rhocall/rhocall/cli.py", line 172, in annotate
    run_annotate_var(
NameError: global name 'run_annotate_var' is not defined

**Comment by dnil** [comment]
How about now? :-]

**Comment by henrikstranneheim** [comment]
rhocall annotate -r 118_sorted_md_brecal_gvcf_vrecal_comb_BOTH.roh ../develop/118/analysis/118/bwa/118_sorted_md_brecal_gvcf_vrecal_comb_BOTH.bcf -o test.vcf.roh.vcf
Traceback (most recent call last):
  File "/mnt/hds/proj/cust003/develop/modules/miniconda2/envs/mip4.0/bin/rhocall", line 11, in <module>
    load_entry_point('rhocall', 'console_scripts', 'rhocall')()
  File "/mnt/hds/proj/cust003/develop/modules/miniconda2/envs/mip4.0/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/mnt/hds/proj/cust003/develop/modules/miniconda2/envs/mip4.0/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/mnt/hds/proj/cust003/develop/modules/miniconda2/envs/mip4.0/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/mnt/hds/proj/cust003/develop/modules/miniconda2/envs/mip4.0/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mnt/hds/proj/cust003/develop/modules/miniconda2/envs/mip4.0/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/mnt/hds/proj/cust003/modules/rhocall/rhocall/cli.py", line 178, in annotate
    output=output
  File "/mnt/hds/proj/cust003/modules/rhocall/rhocall/run_annotate_var.py", line 58, in run_annotate_var
    var = next(proband_vcf)
  File "cyvcf2/cyvcf2.pyx", line 377, in cyvcf2.cyvcf2.VCF.__next__ (cyvcf2/cyvcf2.c:10778)
StopIteration

**Comment by dnil** [comment]
Mismatched variant and roh files were not handled gracefully. 'soz!
